version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_database
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  # redis:
  #   image: bitnami/redis:latest
  #   restart: always
  #   environment:
  #     - REDIS_PASSWORD=example
  #   ports: 
  #     - 6379:6379

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
     - db